### ISSUE TITLE
bug: does not reach return when input is identical

### ISSUE THREAD

**Issue by yetzt** [junosuarez/url-relative#3]
when `from` and `to` are the same, the function never returns

``` javascript
var ur = require("url-relative");
console.log(ur("https://example.com/test", "https://example.com/test"));
```

**Comment by felixfbecker** [comment]
Just noticed this too. This is really dangerous because Node will go into an infinite loop, block the event loop and unable to process any requests. If the URL is in some way from user input, which is not unlikely, this is a DDoS attack vulnerability.

**Comment by yetzt** [comment]
thanks for fixing! 👍

**Comment by alon24** [comment]
@junosuarez hi, I use "connect-sourcemaps" which uses this lib. and now my audit shows errors.
I see you have a fix, can you publish it, so that i can contact the "connect-sourcemaps" to upgrade?
